[package]
name = "bot_maid_3"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1.39.2"
twilight-cache-inmemory = "0.15.4"
twilight-gateway = "0.15.4"
twilight-http = "0.15.4"
twilight-model = "0.15.4"
